In [50]:
# Check if on Colab and mount Drive
COLAB = False
try:
    from google import colab
    COLAB = True
except:
    pass

if COLAB:
    from google.colab import drive, userdata
    drive.mount('/content/drive')

REPO_PATH = '/content/drive/MyDrive/ep_populism_classification' if COLAB else str(Path("../../").resolve())

import sys
sys.path.append(REPO_PATH)

# Git config and pull latest
if COLAB:
    token = userdata.get('GITHUB_TOKEN')
    username = "gransera"
    repo = "ep_populism_classification"

    !git -C {REPO_PATH} config user.email "antonia.granser@gmail.com"
    !git -C {REPO_PATH} config user.name "Antonia Granser"
    !git -C {REPO_PATH} remote set-url origin https://{username}:{token}@github.com/{username}/{repo}.git
    !git -C {REPO_PATH} pull origin main

print("Ready")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
From https://github.com/gransera/ep_populism_classification
 * branch            main       -> FETCH_HEAD
Already up to date.
Ready

In [51]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Inference run"
!git -C {REPO_PATH} push origin main

[main b6d19a1] Inference run
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite notebooks/02_model_application_elite.ipynb (95%)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 72.83 KiB | 4.05 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/gransera/ep_populism_classification.git
   07d991f..b6d19a1  main -> main

## Set up

In [52]:
from pathlib import Path

import pandas as pd
import numpy as np

from transformers import pipeline
from tqdm.notebook import tqdm

import torch

In [53]:
base_path     = Path("/content/drive/MyDrive/ep_populism_classification" if COLAB else "../../")
data_path     = base_path / "data/datasets"
model_path    = base_path / "models/classifiers"
output_folder = base_path / "outputs/predictions"

## Load data

In [54]:
# Load full dataset
df = pd.read_csv(data_path / "parllaw_preprocessed.csv")

# Drop the dictionary tokenization columns
df = df.drop(columns=['sentence_pre'])

print(len(df))
print(df.head(5))

4055401
  unique_id  speech_id  sentence_id        speaker       party        date  \
0       1_1          1            1  Daniel Freund  Greens/EFA  2024-04-25
1       1_2          1            2  Daniel Freund  Greens/EFA  2024-04-25
2       1_3          1            3  Daniel Freund  Greens/EFA  2024-04-25
3       1_4          1            4  Daniel Freund  Greens/EFA  2024-04-25
4       1_5          1            5  Daniel Freund  Greens/EFA  2024-04-25

                                              agenda  period  year  \
0  2. Interinstitutional Body for Ethical Standar...       9  2024
1  2. Interinstitutional Body for Ethical Standar...       9  2024
2  2. Interinstitutional Body for Ethical Standar...       9  2024
3  2. Interinstitutional Body for Ethical Standar...       9  2024
4  2. Interinstitutional Body for Ethical Standar...       9  2024

                                            sentence
0                  Madam President, dear colleagues!
1                     Politics must not be for sale.
2  It cannot be that political decisions in this ...
3  Whether Qatar, Russia, or China – especially w...
4  Even below the threshold of criminal law, belo...

In [55]:
# Check sentence lenght metrics
lengths = df['sentence'].str.split().str.len()

print(f"Average length: {lengths.mean():.1f} words")
print(f"Minimum length: {lengths.min()} words")
print(f"Maximum length: {lengths.max()} words")
print(f"Median length:  {lengths.median():.1f} words")

Average length: 24.1 words
Minimum length: 1 words
Maximum length: 803 words
Median length:  22.0 words

In [7]:
# Check risk of truncation
at_risk = (lengths > 380).sum()
print(f"\nOver 380 words: {at_risk} sentences ({at_risk/len(df)*100:.2f}%)")

Over 380 words: 26 sentences (0.00%)

In [9]:
# Check the distribution more carefully
print(lengths.describe())
print(f"\n95th percentile: {lengths.quantile(0.95):.0f} words")
print(f"99th percentile: {lengths.quantile(0.99):.0f} words")

count    4.055401e+06
mean     2.414083e+01
std      1.474740e+01
min      1.000000e+00
25%      1.400000e+01
50%      2.200000e+01
75%      3.100000e+01
max      8.030000e+02
Name: sentence, dtype: float64

95th percentile: 51 words
99th percentile: 71 words

## Load model

In [56]:
model_folder = model_path / "anti_elitism/anti_elitism_roberta_large_e2"

classifier = pipeline(
    task='text-classification',
    model=model_folder,
    device=0 if torch.cuda.is_available() else -1,
    top_k=None
)

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

### Settings

In [57]:
BATCH_SIZE   = 256
CHUNK_SIZE   = 9984
output_file  = output_folder / "anti_elitism_robertalarge_full_predictions.csv"

## Data inference

In [58]:
# Resume logic
if output_file.exists():
    done      = pd.read_csv(output_file)
    start_row = len(done)
    print(f"Resuming from row {start_row}/{len(df)}")
else:
    start_row = 0
    print(f"Starting fresh — {len(df)} rows total")

Resuming from row 1148224/4055401

In [59]:
# Inference in chunks
for chunk_start in tqdm(range(start_row, len(df), CHUNK_SIZE), desc="Chunks"):
    chunk_end = min(chunk_start + CHUNK_SIZE, len(df))
    chunk     = df.iloc[chunk_start:chunk_end]

    preds = list(tqdm(
        classifier(
          chunk['sentence'].tolist(),
          batch_size=BATCH_SIZE,
          truncation=True,
          max_length=512
      ),
      total=len(chunk),
      desc="Samples",
      leave=True
    ))

    chunk_df = pd.DataFrame({
        'unique_id':   chunk['unique_id'].values,
        'prob_class0': [p[0]['score'] for p in preds],
        'prob_class1': [p[1]['score'] for p in preds],
    })

    # Append to CSV — header only on first write
    chunk_df.to_csv(output_file, mode='a', header=chunk_start == start_row == 0, index=False)

print(f"Done — results saved to {output_file}")

Chunks:   0%|          | 0/292 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/9984 [00:00<?, ?it/s]

Samples:   0%|          | 0/1833 [00:00<?, ?it/s]

Done — results saved to /content/drive/MyDrive/ep_populism_classification/outputs/predictions/anti_elitism_robertalarge_full_predictions.csv

In [ ]:
""" Simpliefied version ------
texts = df['sentence'].tolist()

preds = classifier(texts, batch_size=32, truncation=True, max_length=512)

preds_df = pd.DataFrame({
    'unique_id':   df['unique_id'],
    'prob_class0': [p[0]['score'] for p in preds],
    'prob_class1': [p[1]['score'] for p in preds],
})

pred_df.head()
"""

## Reload model

In [60]:
# Load full results and apply threshold
preds_df = pd.read_csv(output_file)

In [61]:
preds_df.head()

  unique_id  prob_class0  prob_class1
0       1_1     0.945230     0.054770
1       1_2     0.782590     0.217410
2       1_3     0.764966     0.235034
3       1_4     0.918710     0.081290
4       1_5     0.885458     0.114542

In [62]:
# Check for duplicates
print(f"Total rows:      {len(preds_df)}")
print(f"Unique IDs:      {preds_df['unique_id'].nunique()}")
print(f"Duplicates:      {preds_df.duplicated(subset='unique_id').sum()}")

Total rows:      4055401
Unique IDs:      4055401
Duplicates:      0

In [63]:
# Apply best performing threshold

THRESHOLD = 0.675
preds_df['pred_label'] = (preds_df['prob_class1'] >= THRESHOLD).astype(int)
preds_df.head()

  unique_id  prob_class0  prob_class1  pred_label
0       1_1     0.945230     0.054770           0
1       1_2     0.782590     0.217410           0
2       1_3     0.764966     0.235034           0
3       1_4     0.918710     0.081290           0
4       1_5     0.885458     0.114542           0

In [64]:
# Save file
preds_df.to_csv(output_folder / "anti_elitism_robertalarge_full_predictions_threshold.csv", index=False)

In [65]:
# Merge prediction df with original df
    # in fresh session necessary to load parllaw corpus again
df_final = df.merge(preds_df, on='unique_id')
df_final.head()

,unique_id,speech_id,sentence_id,speaker,party,date,agenda,period,year,sentence,prob_class0,prob_class1,pred_label
0,1_1,1,1,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Madam President, dear colleagues!",0.945230,0.054770,0
1,1_2,1,2,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,Politics must not be for sale.,0.782590,0.217410,0
2,1_3,1,3,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,It cannot be that political decisions in this ...,0.764966,0.235034,0
3,1_4,1,4,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Whether Qatar, Russia, or China – especially w...",0.918710,0.081290,0
4,1_5,1,5,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Even below the threshold of criminal law, belo...",0.885458,0.114542,0

In [67]:
# Change column names to "elite"
df_final = df_final.rename(columns={
    'prob_class0': 'elite_prob_class0',
    'prob_class1': 'elite_prob_class1',
    'pred_label':  'elite_pred_label'
})

In [68]:
# Safe final file
df_final.to_csv(output_folder / "ep_speeches_anti_elitism.csv", index=False)

In [71]:
df_final.head()

,unique_id,speech_id,sentence_id,speaker,party,date,agenda,period,year,sentence,elite_prob_class0,elite_prob_class1,elite_pred_label
0,1_1,1,1,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Madam President, dear colleagues!",0.945230,0.054770,0
1,1_2,1,2,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,Politics must not be for sale.,0.782590,0.217410,0
2,1_3,1,3,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,It cannot be that political decisions in this ...,0.764966,0.235034,0
3,1_4,1,4,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Whether Qatar, Russia, or China – especially w...",0.918710,0.081290,0
4,1_5,1,5,Daniel Freund,Greens/EFA,2024-04-25,2. Interinstitutional Body for Ethical Standar...,9,2024,"Even below the threshold of criminal law, belo...",0.885458,0.114542,0

In [ ]:
len(df_final[elite_pred_label == 1])

In [72]:
df_final['elite_pred_label'].value_counts()

elite_pred_label
0    4055401
Name: count, dtype: int64

In [76]:
print(df_final['elite_prob_class1'].describe())
print(f"\nTop 10 highest scores:")
print(df_final.nlargest(10, 'elite_prob_class1')[['unique_id', 'elite_prob_class1', 'elite_prob_class0', 'elite_pred_label']])

count    4.055401e+06
mean     4.415243e-02
std      8.306489e-02
min      1.762965e-03
25%      7.493674e-03
50%      1.324476e-02
75%      3.192681e-02
max      4.999972e-01
Name: elite_prob_class1, dtype: float64

Top 10 highest scores:
         unique_id  elite_prob_class1  elite_prob_class0  elite_pred_label
3533211   473236_2           0.499997           0.500003                 0
1646875   224118_5           0.499996           0.500004                 0
2062922   296915_9           0.499994           0.500006                 0
238234    21119_15           0.499994           0.500006                 0
3436505  465041_33           0.499992           0.500008                 0
1421031   180810_7           0.499991           0.500009                 0
1273804   153058_9           0.499990           0.500010                 0
2205518   318370_7           0.499990           0.500010                 0
1228722   141850_1           0.499989           0.500011                 0
1141692  125206_13           0.499988           0.500012                 0

## Synchronize with Git

In [69]:
# Clear widget metadata before saving
from IPython.display import clear_output
clear_output()

In [70]:
!git -C {REPO_PATH} add .
!git -C {REPO_PATH} commit -m "Run inference for anti-elitism dimension"
!git -C {REPO_PATH} push origin main

[main 732a63b] Run inference for anti-elitism dimension
 1 file changed, 1 insertion(+), 1 deletion(-)
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 179.07 KiB | 4.48 MiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/gransera/ep_populism_classification.git
   b6d19a1..732a63b  main -> main